apiVersion: v1
kind: Service
metadata:
  name: churn-api-service
  labels:
    app: churn-api
spec:
  type: ClusterIP
  selector:
    app: churn-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
